/vis/verbose 1
/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style surface
/vis/viewer/set/background black

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/setRGBA gamma     0 1 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA proton    1 1 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e-        0 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e+        0 1 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron   1 1 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA deuteron  1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA triton    1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA alpha     1 0 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA ion       1 0 0 1

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 50

# Decorations
/vis/set/textColour yellow
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! PW 1 : Geometry_PW_2

# Axes
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo

/vis/geometry/set/visibility logWorld 0 false
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true

